package entity;
// Generated Feb 28, 2019 2:46:56 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * BuyerBuyProduct generated by hbm2java
 */
public class BuyerBuyProduct  implements java.io.Serializable {


     private Integer buyerId;
     private Integer productId;
     private Date paymentDate;
     private float amount;
     private int quantity;

    public BuyerBuyProduct() {
    }

    public BuyerBuyProduct(Integer buyerId, Integer productId, Date paymentDate, float amount, int quantity)
    {
        this.buyerId = buyerId;
        this.productId = productId;
        this.paymentDate = paymentDate;
        this.amount = amount;
        this.quantity = quantity;
    }

    public Integer getBuyerId()
    {
        return buyerId;
    }

    public void setBuyerId(Integer buyerId)
    {
        this.buyerId = buyerId;
    }

    public Integer getProductId()
    {
        return productId;
    }

    public void setProductId(Integer productId)
    {
        this.productId = productId;
    }

    public Date getPaymentDate()
    {
        return paymentDate;
    }

    public void setPaymentDate(Date paymentDate)
    {
        this.paymentDate = paymentDate;
    }

    public float getAmount()
    {
        return amount;
    }

    public void setAmount(float amount)
    {
        this.amount = amount;
    }

    public int getQuantity()
    {
        return quantity;
    }

    public void setQuantity(int quantity)
    {
        this.quantity = quantity;
    }

    
    
   
}


