package entity;
// Generated Feb 28, 2019 2:46:56 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Buyer generated by hbm2java
 */
public class Buyer implements java.io.Serializable
{

    private Integer id;
    private String value;
    private Integer userId;

    public Buyer()
    {
    }

    
    
    public Buyer(String value, Integer userId)
    {
        this.value = value;
        this.userId = userId;
    }

    public Integer getId()
    {
        return id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public String getValue()
    {
        return value;
    }

    public void setValue(String value)
    {
        this.value = value;
    }

    public Integer getUserId()
    {
        return userId;
    }

    public void setUserId(Integer userId)
    {
        this.userId = userId;
    }

    @Override
    public String toString()
    {
        return "Buyer{" + "id=" + id + ", value=" + value + ", userId=" + userId + '}';
    }

}
