package entity;
// Generated Feb 28, 2019 2:46:56 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer id;
     private Integer sellerId;
     private String name;
     private String description;
     private String manufacturingName;
     private Date manufacturingDate;
     private Date expirationDate;
     private int quantity;
     private Date offeredDate;
     private Date finishDate;
     

    public Product() {
    }

    public Product(Integer sellerId, String name, String description, String manufacturingName, Date manufacturingDate, Date expirationDate, int quantity, Date offeredDate, Date finishDate)
    {
        this.sellerId = sellerId;
        this.name = name;
        this.description = description;
        this.manufacturingName = manufacturingName;
        this.manufacturingDate = manufacturingDate;
        this.expirationDate = expirationDate;
        this.quantity = quantity;
        this.offeredDate = offeredDate;
        this.finishDate = finishDate;
    }

    public Integer getId()
    {
        return id;
    }

    public void setId(Integer id)
    {
        this.id = id;
    }

    public Integer getSellerId()
    {
        return sellerId;
    }

    public void setSellerId(Integer sellerId)
    {
        this.sellerId = sellerId;
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public String getDescription()
    {
        return description;
    }

    public void setDescription(String description)
    {
        this.description = description;
    }

    public String getManufacturingName()
    {
        return manufacturingName;
    }

    public void setManufacturingName(String manufacturingName)
    {
        this.manufacturingName = manufacturingName;
    }

    public Date getManufacturingDate()
    {
        return manufacturingDate;
    }

    public void setManufacturingDate(Date manufacturingDate)
    {
        this.manufacturingDate = manufacturingDate;
    }

    public Date getExpirationDate()
    {
        return expirationDate;
    }

    public void setExpirationDate(Date expirationDate)
    {
        this.expirationDate = expirationDate;
    }

    public int getQuantity()
    {
        return quantity;
    }

    public void setQuantity(int quantity)
    {
        this.quantity = quantity;
    }

    public Date getOfferedDate()
    {
        return offeredDate;
    }

    public void setOfferedDate(Date offeredDate)
    {
        this.offeredDate = offeredDate;
    }

    public Date getFinishDate()
    {
        return finishDate;
    }

    public void setFinishDate(Date finishDate)
    {
        this.finishDate = finishDate;
    }

    @Override
    public String toString()
    {
        return "Product{" + "id=" + id + ", sellerId=" + sellerId + ", name=" + name + ", description=" + description + ", manufacturingName=" + manufacturingName + ", manufacturingDate=" + manufacturingDate + ", expirationDate=" + expirationDate + ", quantity=" + quantity + ", offeredDate=" + offeredDate + ", finishDate=" + finishDate + '}';
    }

    

}


